services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    container_name: task-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
    depends_on:
      - mongo
      - redis
    command: npm start
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge