#sonar-project.properties

sonar.projectKey=Node-Task-App
sonar.projectName=Node-Task-App
sonar.projectVersion=1.0

# scan your entire repo except node_modules
sonar.sources=.

# optional but useful
sonar.exclusions=node_modules/**

# import ESLint issues (generated in CI)
sonar.eslint.reportPaths=eslint-report.json

# connect to your SonarQube instance (from GitHub secrets)
# sonar.host.url is set via SONAR_HOST_URL environment variable in the workflow