#mongo.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.env }}-mongo"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.env }}-mongo"
  template:
    metadata:
      labels:
        app: "{{ .Values.env }}-mongo"
    spec:
      containers:
      - name: mongo
        image: "{{ .Values.mongo.image }}"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.env }}-mongo"
spec:
  selector:
    app: "{{ .Values.env }}-mongo"
  ports:
  - port: 27017
    targetPort: 27017
