#task-api.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.env }}-{{ .Values.app.name }}"
spec:
  replicas: {{ .Values.app.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: "{{ .Values.env }}-{{ .Values.app.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.env }}-{{ .Values.app.name }}"
    spec:
      containers:
      - name: "{{ .Values.app.name }}"
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        ports:
        - containerPort: {{ .Values.app.port }}
        env:
        - name: MONGO_URI
          value: "mongodb://{{ .Values.env }}-mongo:27017/taskdb"
        - name: REDIS_HOST
          value: "{{ .Values.env }}-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: PORT
          value: "{{ .Values.app.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.env }}-{{ .Values.app.name }}"
spec:
  selector:
    app: "{{ .Values.env }}-{{ .Values.app.name }}"
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.app.port }}
  type: ClusterIP
