app:
  name: task-api
  image:
    repository: usmanshabbir/task-api
    tag: latest-v31
  replicas: 6
  port: 3000
mongo:
  image: mongo:6.0
redis:
  image: redis:latest
nginx:
  image: nginx:latest
  nodePort: 30080
notifications:
  enabled: true
env: prod
