name: Deploy to K3s

on:
  push:
    branches:
      - TS-677  # The branch that triggers the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS EKS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t usmanshabbir/task-api:latest .
          docker push usmanshabbir/task-api:latest

      - name: Trigger K3s Deployment on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            kubectl rollout restart deployment task-api
            kubectl rollout status deployment task-api
